language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t testme -f Dockerfile.dev .

script:
  - docker run -e CI=true testme npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  end: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-460911871351"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"